
import { Bus } from './types';

export const POPULAR_CITIES = [
  "Mumbai", "Pune", "Bangalore", "Chennai", "Delhi", "Manali", 
  "Hyderabad", "Kolkata", "Goa", "Ahmedabad", "Jaipur", "Chandigarh", "Shimla"
];

export const MOCK_BUSES: Bus[] = [
  // Existing Routes
  {
    id: '1',
    busNumber: 'MH-12-BF-4455',
    name: 'Eagle Express',
    type: 'AC',
    source: 'Mumbai',
    destination: 'Pune',
    departureTime: '08:00 AM',
    arrivalTime: '11:00 AM',
    totalSeats: 40,
    availableSeats: 12,
    price: 450,
    rating: 4.5
  },
  {
    id: '2',
    busNumber: 'MH-14-GH-1234',
    name: 'Neeta Travels',
    type: 'Sleeper',
    source: 'Mumbai',
    destination: 'Pune',
    departureTime: '10:30 AM',
    arrivalTime: '01:30 PM',
    totalSeats: 30,
    availableSeats: 0,
    price: 600,
    rating: 4.2
  },
  {
    id: '3',
    busNumber: 'KA-01-EE-9988',
    name: 'SRS Travels',
    type: 'Non-AC',
    source: 'Bangalore',
    destination: 'Chennai',
    departureTime: '09:15 PM',
    arrivalTime: '05:00 AM',
    totalSeats: 45,
    availableSeats: 5,
    price: 350,
    rating: 3.8
  },
  {
    id: '4',
    busNumber: 'MH-12-AS-0001',
    name: 'Prasanna Purple',
    type: 'Semi-Sleeper',
    source: 'Pune',
    destination: 'Mumbai',
    departureTime: '05:00 PM',
    arrivalTime: '08:00 PM',
    totalSeats: 40,
    availableSeats: 25,
    price: 400,
    rating: 4.7
  },
  {
    id: '5',
    busNumber: 'DL-01-XX-5566',
    name: 'Himachal Express',
    type: 'AC',
    source: 'Delhi',
    destination: 'Manali',
    departureTime: '08:00 PM',
    arrivalTime: '07:00 AM',
    totalSeats: 40,
    availableSeats: 2,
    price: 1200,
    rating: 4.9
  },

  // New Routes & Buses
  {
    id: '6',
    busNumber: 'KA-05-MM-1122',
    name: 'Orange Tours',
    type: 'AC',
    source: 'Bangalore',
    destination: 'Hyderabad',
    departureTime: '10:00 PM',
    arrivalTime: '06:30 AM',
    totalSeats: 36,
    availableSeats: 18,
    price: 1100,
    rating: 4.4
  },
  {
    id: '7',
    busNumber: 'TS-09-UB-4455',
    name: 'Morning Star Travels',
    type: 'Sleeper',
    source: 'Hyderabad',
    destination: 'Bangalore',
    departureTime: '09:30 PM',
    arrivalTime: '06:00 AM',
    totalSeats: 30,
    availableSeats: 4,
    price: 1450,
    rating: 4.6
  },
  {
    id: '8',
    busNumber: 'RJ-14-BT-9900',
    name: 'RSRTC Gold Line',
    type: 'AC',
    source: 'Delhi',
    destination: 'Jaipur',
    departureTime: '06:00 AM',
    arrivalTime: '11:30 AM',
    totalSeats: 42,
    availableSeats: 30,
    price: 550,
    rating: 4.1
  },
  {
    id: '9',
    busNumber: 'RJ-14-BT-9901',
    name: 'Zingbus Premium',
    type: 'AC',
    source: 'Delhi',
    destination: 'Jaipur',
    departureTime: '02:00 PM',
    arrivalTime: '07:30 PM',
    totalSeats: 35,
    availableSeats: 0,
    price: 850,
    rating: 4.8
  },
  {
    id: '10',
    busNumber: 'MH-01-GA-7788',
    name: 'Purple Metrolink',
    type: 'AC',
    source: 'Pune',
    destination: 'Goa',
    departureTime: '09:00 PM',
    arrivalTime: '07:30 AM',
    totalSeats: 36,
    availableSeats: 15,
    price: 1200,
    rating: 4.3
  },
  {
    id: '11',
    busNumber: 'GA-03-ZZ-3344',
    name: 'Kadamba Transport',
    type: 'Non-AC',
    source: 'Goa',
    destination: 'Pune',
    departureTime: '07:00 PM',
    arrivalTime: '05:30 AM',
    totalSeats: 45,
    availableSeats: 40,
    price: 650,
    rating: 3.9
  },
  {
    id: '12',
    busNumber: 'TN-01-CH-5566',
    name: 'Parveen Travels',
    type: 'Sleeper',
    source: 'Chennai',
    destination: 'Bangalore',
    departureTime: '11:15 PM',
    arrivalTime: '06:00 AM',
    totalSeats: 30,
    availableSeats: 8,
    price: 950,
    rating: 4.5
  },
  {
    id: '13',
    busNumber: 'GJ-01-AH-1100',
    name: 'Patel Tours',
    type: 'AC',
    source: 'Ahmedabad',
    destination: 'Mumbai',
    departureTime: '10:00 PM',
    arrivalTime: '06:00 AM',
    totalSeats: 36,
    availableSeats: 2,
    price: 1300,
    rating: 4.4
  },
  {
    id: '14',
    busNumber: 'WB-02-KK-9988',
    name: 'Shyamoli Paribahan',
    type: 'AC',
    source: 'Kolkata',
    destination: 'Bhubaneswar',
    departureTime: '08:30 PM',
    arrivalTime: '05:00 AM',
    totalSeats: 40,
    availableSeats: 14,
    price: 800,
    rating: 4.2
  },
  {
    id: '15',
    busNumber: 'CH-01-TD-5544',
    name: 'Chandigarh Transport',
    type: 'Semi-Sleeper',
    source: 'Chandigarh',
    destination: 'Shimla',
    departureTime: '05:00 AM',
    arrivalTime: '09:00 AM',
    totalSeats: 40,
    availableSeats: 35,
    price: 450,
    rating: 4.0
  },
  {
    id: '16',
    busNumber: 'HP-01-SH-1122',
    name: 'Himalayan Nomad',
    type: 'AC',
    source: 'Shimla',
    destination: 'Delhi',
    departureTime: '08:00 PM',
    arrivalTime: '06:00 AM',
    totalSeats: 32,
    availableSeats: 10,
    price: 1100,
    rating: 4.7
  },
  {
    id: '17',
    busNumber: 'KA-05-HYD-001',
    name: 'VRL Travels',
    type: 'Sleeper',
    source: 'Bangalore',
    destination: 'Hyderabad',
    departureTime: '11:45 PM',
    arrivalTime: '08:30 AM',
    totalSeats: 30,
    availableSeats: 0,
    price: 1800,
    rating: 4.8
  }
];
